### PR TITLE
fortinet_fortios added

### PR DESCRIPTION
**Pull request by viktorkertesz**
# Description

This PR is addressing to implement Fortinet FortiOS platform. This platform is used by FortiGate firewalls. The CLI is pretty unique compared to juniper or cisco. There is no "config" mode, all configuration is part of a block, therefore I did not implemented privilege levels.

### added
- configuring multiple commands in batch mode
- removing and restoring paging (which is on by default)
- auto-accepting post-login banner
- handling multi VDOM mode
  - changing VDOM/context by calling conn.context() method
### removed
- send_config(s) methods are not appropriate for this platform, use send_commands instead

## Example
```
    data = {
        "host": host,
        "platform": "fortinet_fortios",
        "auth_username": username,
        "auth_password": password,
        "auth_strict_key": False,
        "transport": "asyncssh",
        "ssh_config_file": True,
        "channel_log": f"{host}.log",
    }

    async with AsyncScrapli(**data) as conn:
        conn: AsyncFortinetFortiOSDriver  # satisfy IDE
        version = await conn.send_command("get system status | grep Version:")
        config = """\
        config global
            config system console
                set output more
            end
        end
        """
        responses = await conn.send_commands(config.splitlines(), batch_mode=True)
```

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

Implemented prompt pytest rules. I tested the code part on my lab devices.

# Checklist:

- [X] My code follows the style guidelines of this project (no GitHub actions compalints! run `make lint` before
 committing!)
- [X] I have commented my code, pydocstyle and darglint are happy, docstrings are in google docstring format, and all
 docstrings include a summary, args, returns and raises fields (even if N/A)
- [X] I have added tests that prove my fix is effective or that my feature works, if adding "functional" tests please
 note if there are any considerations for the vrnetlab setup
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by carlmontanari** [comment]
looks excellent as always @viktorkertesz ! would you mind adding a quick line to the changelog and the table in the docs showing the platforms? (I always forget to do these, so trying to stay on top of it :D)

**Comment by realvitya** [comment]
Hi @carlmontanari ,

Sure thing! Do whatever necessary and i forgot 😁

Viktor

**Comment by viktorkertesz** [comment]
@carlmontanari I added docs you mentioned. I realized docs bugs, I'll do a separate PR for that shortly.

**Comment by carlmontanari** [comment]
you rock! will take look at the docs one probably his weekend and get that merged too! thanks again!!

**Pull request merged**
