### PR TITLE
add Cisco CBS

### PR DESCRIPTION
**Pull request by andreygrechin**
# Description
Hi, 

This PR adds Cisco small business switches. This family includes different models SF/SG/CBS/220/250/350/550 which are based on TextView CLI.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested on live SG250-08 with version 2.5.7.85, ntc-templates 2.2.2.

# Checklist:

- [X] My code follows the style guidelines of this project (no GitHub actions compalints! run `make lint` before
 committing!)
- [X] I have commented my code, pydocstyle and darglint are happy, docstrings are in google docstring format, and all
 docstrings include a summary, args, returns and raises fields (even if N/A)
- [X] I have added tests that prove my fix is effective or that my feature works, if adding "functional" tests please
 note if there are any considerations for the vrnetlab setup
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by carlmontanari** [comment]
Hey @andreygrechin this looks great! Thanks a bunch for adding this!

**Comment by andreygrechin** [comment]
Cool 😊 
@carlmontanari Thanks a million for your amazing toolset.

**Comment by lifeofdave** [comment]
For anyone else that can SSH into their CBS device but finds this doesn't work, make sure you also enable ‘SSH User Authentication by Password' on your device. Full steps below:

1.Login to web UI and set display to advanced
2. Security → TCP/UDP Services → Enable ‘SSH Service’ 
    At this stage you can login via SSH but it then shows a prompt for username and then password - this doesn’t work with this scrapli, so you must do stage 3
    
3. Security → SSH Server → SSH User Authentication → Enable ‘SSH User Authentication by Password:’
    If it’s all worked you’ll be able to login via SSH using you username and password as you would for any other standard SSH session. EG $ ssh dave@10.0.3.22, and then scrapli should also connect ok.

**Comment by carlmontanari** [comment]
awesome! thanks for sharing @lifeofdave !

**Pull request merged**
