### PR TITLE
Adding Zyxel IES DSLAMs driver support

### PR DESCRIPTION
**Pull request by codingnetworksb**
# Description

Adding Zyxel IES DSLAMs driver support.

I'm working with some automation tasks on  Zyxel IES 5000 Series DSLAMs. I'm migrating my implementations from pyats-genie/unicon to scrapli and decided to create a new driver for Zyxel IES 5000 Series DSLAMs. These are legacy devices and the Operating system doesn't have a name. 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

I have tested this driver on production devices. Zyxel IES 5000 Series DSLAMs.

# Checklist:

- [X] My code follows the style guidelines of this project (no GitHub actions complaints! run `make lint` before
 committing!)
- [X] I have commented my code, pydocstyle and darglint are happy, docstrings are in google docstring format, and all
 docstrings include a summary, args, returns and raises fields (even if N/A)
- [X] I have added tests that prove my fix is effective or that my feature works, if adding "functional" tests please
 note if there are any considerations for the vrnetlab setup
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by carlmontanari** [comment]
hey @codingnetworksb you are on a roll :D 

quick question: why the two priv levels if they appear the same? if theres no distinction between levels you can just omit the configuration level and do everything with "send_command"(s) -- that is the prevailing "style" here I think (for no specific reason, just how it happened)

**Comment by codingnetworksb** [comment]
Hi @carlmontanari , i plan to build a code that i can reuse for different drivers. Deploying a configuration i would like to make use of  send_config no matter witch driver is being used.

**Comment by codingnetworksb** [comment]
> maybe we could make a base platform that has the "normal" behavior (just exec mode, no config mode), then a variant called "with-config" (or something more clever than that!). how does that sound? that should be best of both worlds I think -- then we can just add a comment on the "with-config" one that links to this and tells people what it does.

Ok for me. I will do it and comment back when is ready to check.

**Comment by carlmontanari** [comment]
> Ok for me. I will do it and comment back when is ready to check.

ok cool! ill merge the one that didnt have this then we can check back in whenever ya add the variant on this and the other one!

thanks a bunch for all this work!

**Comment by codingnetworksb** [comment]
Hi @carlmontanari, i decided to support the prevailing "style". I removed the config mode and won't create a variant. Will do the same with the nokia_sros variant.

**Comment by carlmontanari** [comment]
cool, works for me! thanks a bunch @codingnetworksb 🚀

**Pull request merged**
